//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Profile
	{
		private string m_FirstName;
		private string m_LastName;
		private string m_NickName;
		private int m_Age;
		public Profile (string firstname,string lastname,string nickname,int age)
		{
			FirstName = firstname;
			lastname = lastname;
			nickname = nickname;
			Age = age;

		}
		public string FirstName
		{
			get { return m_FirstName; }
			set { m_FirstName = value; }
		}
		public string LastName
		{
			get { return m_LastName; }
			set { m_LastName = value; }
		}
		public string NickName
		{
			get { return m_NickName; }
			set { m_NickName = value; }
		}
		public int Age
		{
			get { return m_Age; }
			set { m_Age = value; }
		}


	}
}

